#!/usr/bin/env python3
"""Seed the DRGP roads registry from on-disk GIS segment GeoJSON.

Reads:  data/gis_states/{andhra|telangana}/index/segments/{district_id}.geojson
Writes: roads (+ optional sync from survey_segment_status)

Official / external identifiers stored:
  - district_id     LGD code (govt administrative)
  - osm_id          OpenStreetMap way id (third-party map data)
  - osm_ref         NH/SH route number when OSM has ref= (not unique per segment)

Generated by SmartRoad:
  - id / gis_segment_id   {district_id}_{osm_id}  (survey compat)
  - road_code             SR-{AP|TG}-{district}-{CLASS}-{osm_id}

Usage (on server, from repo root with venv + .env):
  python scripts/seed_roads_registry.py --migrate-only
  python scripts/seed_roads_registry.py --state both
  python scripts/seed_roads_registry.py --state telangana --district 518
  python scripts/seed_roads_registry.py --state both --sync-status --snap-potholes
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from dotenv import load_dotenv

load_dotenv(ROOT / ".env", override=True)

STATE_META = {
    "andhra": {"state_id": 1, "abbrev": "AP"},
    "telangana": {"state_id": 2, "abbrev": "TG"},
}

CLASS_ABBREV = {
    "nh": "NH",
    "sh": "SH",
    "mdr": "MDR",
    "other": "OTH",
}

INSERT_TEMPLATE = (
    "(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,"
    "ST_SetSRID(ST_GeomFromGeoJSON(%s),4326),"
    "ST_Centroid(ST_SetSRID(ST_GeomFromGeoJSON(%s),4326)),"
    "%s,%s)"
)


def _segment_id(props: dict, district_id: str) -> str:
    if props.get("segment_id"):
        return str(props["segment_id"])
    osm = props.get("osm_id") or props.get("osmid") or props.get("id") or "0"
    return f"{district_id}_{osm}"


def _road_code(state_abbrev: str, district_id: str, road_class: str, osm_id: int | str) -> str:
    cls = CLASS_ABBREV.get((road_class or "other").lower(), "OTH")
    return f"SR-{state_abbrev}-{district_id}-{cls}-{osm_id}"


def _osm_id(props: dict) -> int:
    raw = props.get("osm_id") or props.get("osmid") or props.get("id") or 0
    try:
        return int(raw)
    except (TypeError, ValueError):
        return 0


def apply_migration() -> None:
    import db_utils

    if not db_utils.is_db_configured():
        raise SystemExit("ERROR: DB not configured (.env DB_NAME / DB_USER / DB_PASSWORD)")

    mig = ROOT / "migrations" / "20260720_drgp_road_registry.sql"
    if not mig.is_file():
        raise SystemExit(f"Missing migration file: {mig}")

    sql = mig.read_text(encoding="utf-8")
    conn = db_utils._get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(sql)
        conn.commit()
        print(f"Applied migration: {mig.name}")
    finally:
        conn.close()


def _district_files(state_key: str, district_filter: str | None) -> list[Path]:
    seg_dir = ROOT / "data" / "gis_states" / state_key / "index" / "segments"
    if not seg_dir.is_dir():
        raise SystemExit(
            f"Missing GIS segments dir: {seg_dir}\n"
            f"Run: python tools/gis/clip_roads_to_districts.py --state {state_key}"
        )
    if district_filter:
        p = seg_dir / f"{district_filter}.geojson"
        return [p] if p.is_file() else []
    return sorted(seg_dir.glob("*.geojson"))


def _row_tuple(
    feat: dict,
    *,
    state_key: str,
    state_id: int,
    state_abbrev: str,
    district_id: str,
    import_batch_id: str,
) -> tuple | None:
    props = feat.get("properties") or {}
    geom = feat.get("geometry")
    if not geom or not geom.get("coordinates"):
        return None

    try:
        length_km = float(props.get("length_km") or 0)
    except (TypeError, ValueError):
        length_km = 0.0
    if length_km <= 0:
        return None

    osm_id = _osm_id(props)
    if osm_id <= 0:
        return None

    gid = _segment_id(props, district_id)
    road_class = (props.get("road_class") or "other").lower()
    if road_class not in CLASS_ABBREV:
        road_class = "other"

    name = (props.get("name") or "").strip() or "Unnamed"
    osm_ref = (props.get("ref") or "").strip() or None
    geom_json = json.dumps(geom, separators=(",", ":"))

    return (
        gid,
        _road_code(state_abbrev, district_id, road_class, osm_id),
        gid,
        name,
        osm_ref,
        road_class,
        state_id,
        state_key,
        int(district_id),
        props.get("district_name"),
        length_km,
        osm_id,
        props.get("highway"),
        geom_json,
        geom_json,
        "osm_clip",
        import_batch_id,
    )


def seed_state(
    state_key: str,
    *,
    district_filter: str | None,
    batch_size: int,
    dry_run: bool,
) -> tuple[int, int]:
    meta = STATE_META[state_key]
    files = _district_files(state_key, district_filter)
    if not files:
        print(f"  [{state_key}] no segment files found")
        return 0, 0

    import_batch_id = (
        f"{state_key}-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}-{uuid.uuid4().hex[:8]}"
    )
    total_features = 0
    total_upserted = 0

    if dry_run:
        for fp in files:
            data = json.loads(fp.read_text(encoding="utf-8"))
            total_features += len(data.get("features") or [])
        print(f"  [{state_key}] dry-run: {len(files)} files, {total_features:,} features")
        return total_features, 0

    import db_utils
    from psycopg2.extras import execute_values

    insert_sql = """
        INSERT INTO roads (
            id, road_code, gis_segment_id,
            road_name, osm_ref, road_class,
            state_id, state_key, district_id, district_name,
            length_km, osm_id, osm_highway,
            geom, centroid,
            source, import_batch_id
        ) VALUES %s
        ON CONFLICT (id) DO UPDATE SET
            road_code = EXCLUDED.road_code,
            road_name = EXCLUDED.road_name,
            osm_ref = EXCLUDED.osm_ref,
            road_class = EXCLUDED.road_class,
            state_id = EXCLUDED.state_id,
            state_key = EXCLUDED.state_key,
            district_id = EXCLUDED.district_id,
            district_name = EXCLUDED.district_name,
            length_km = EXCLUDED.length_km,
            osm_id = EXCLUDED.osm_id,
            osm_highway = EXCLUDED.osm_highway,
            geom = EXCLUDED.geom,
            centroid = EXCLUDED.centroid,
            source = EXCLUDED.source,
            import_batch_id = EXCLUDED.import_batch_id,
            updated_at = NOW()
    """

    conn = db_utils._get_conn()
    try:
        for fp in files:
            district_id = fp.stem
            t0 = time.perf_counter()
            data = json.loads(fp.read_text(encoding="utf-8"))
            batch: list[tuple] = []
            file_count = 0

            for feat in data.get("features") or []:
                row = _row_tuple(
                    feat,
                    state_key=state_key,
                    state_id=meta["state_id"],
                    state_abbrev=meta["abbrev"],
                    district_id=district_id,
                    import_batch_id=import_batch_id,
                )
                if not row:
                    continue
                batch.append(row)
                file_count += 1
                total_features += 1

                if len(batch) >= batch_size:
                    with conn.cursor() as cur:
                        execute_values(
                            cur, insert_sql, batch,
                            template=INSERT_TEMPLATE,
                            page_size=batch_size,
                        )
                    conn.commit()
                    total_upserted += len(batch)
                    batch.clear()

            if batch:
                with conn.cursor() as cur:
                    execute_values(
                        cur, insert_sql, batch,
                        template=INSERT_TEMPLATE,
                        page_size=len(batch),
                    )
                conn.commit()
                total_upserted += len(batch)

            elapsed = time.perf_counter() - t0
            print(f"  [{state_key}] {district_id}: {file_count:,} segments in {elapsed:.1f}s")
    finally:
        conn.close()

    return total_features, total_upserted


def sync_survey_status() -> int:
    import db_utils

    conn = db_utils._get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                UPDATE roads r
                SET survey_status = s.status,
                    updated_at = NOW()
                FROM survey_segment_status s
                WHERE r.id = s.segment_id
            """)
            n = cur.rowcount
        conn.commit()
        print(f"Synced survey_status from survey_segment_status: {n:,} rows")
        return n
    finally:
        conn.close()


def snap_potholes(max_distance_m: float = 15.0) -> int:
    import db_utils

    conn = db_utils._get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE potholes p
                SET
                    road_id = sub.road_id,
                    snap_distance_m = sub.dist_m,
                    snapped_at = NOW()
                FROM (
                    SELECT
                        p2.id AS pothole_id,
                        r.id AS road_id,
                        ST_Distance(p2.location::geography, r.geom::geography) AS dist_m
                    FROM potholes p2
                    CROSS JOIN LATERAL (
                        SELECT r.id, r.geom
                        FROM roads r
                        WHERE p2.location IS NOT NULL
                          AND ST_DWithin(p2.location, r.geom, 0.0002)
                        ORDER BY p2.location <-> r.geom
                        LIMIT 1
                    ) r
                    WHERE p2.road_id IS NULL
                ) sub
                WHERE p.id = sub.pothole_id
                  AND sub.dist_m <= %s
                """,
                (max_distance_m,),
            )
            n = cur.rowcount
        conn.commit()
        print(f"Snapped potholes to roads (≤{max_distance_m}m): {n:,} rows")
        return n
    finally:
        conn.close()


def print_summary() -> None:
    import db_utils

    conn = db_utils._get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM roads")
            total = cur.fetchone()[0]
            cur.execute("""
                SELECT state_key, road_class, COUNT(*)
                FROM roads GROUP BY state_key, road_class ORDER BY 1, 2
            """)
            rows = cur.fetchall()
            cur.execute("""
                SELECT road_code, id, road_name, osm_ref, district_name
                FROM roads
                WHERE osm_ref IS NOT NULL AND osm_ref <> ''
                LIMIT 3
            """)
            samples = cur.fetchall()
        print(f"\nRegistry total: {total:,} roads")
        for sk, rc, n in rows:
            print(f"  {sk:10} {rc:6} {n:,}")
        if samples:
            print("\nSample rows with official route ref (NH/SH):")
            for code, gid, name, ref, dname in samples:
                print(f"  {code}  gis={gid}  ref={ref}  {name or dname}")
    finally:
        conn.close()


def main() -> int:
    parser = argparse.ArgumentParser(description="Seed DRGP roads registry from GIS GeoJSON")
    parser.add_argument("--state", choices=("andhra", "telangana", "both"), default="both")
    parser.add_argument("--district", help="Import one LGD district id only (e.g. 518)")
    parser.add_argument("--batch-size", type=int, default=500)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--migrate-only", action="store_true")
    parser.add_argument("--migrate", action="store_true", help="Apply migration before seeding")
    parser.add_argument("--sync-status", action="store_true")
    parser.add_argument("--snap-potholes", action="store_true")
    args = parser.parse_args()

    if args.migrate_only:
        apply_migration()
        return 0

    if args.migrate:
        apply_migration()

    states = ("andhra", "telangana") if args.state == "both" else (args.state,)
    grand_features = 0
    grand_upserted = 0

    if args.dry_run:
        print(f"Seeding roads registry (dry-run)")
        for sk in states:
            n_feat, n_ins = seed_state(
                sk,
                district_filter=args.district,
                batch_size=args.batch_size,
                dry_run=True,
            )
            grand_features += n_feat
            grand_upserted += n_ins
        print(f"\nParsed {grand_features:,} segments (no DB writes)")
        return 0

    import db_utils
    if not db_utils.is_db_configured():
        print("ERROR: DB not configured")
        return 1

    conn = db_utils._get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'roads'
            """)
            if not cur.fetchone():
                print("ERROR: roads table missing. Run: python scripts/seed_roads_registry.py --migrate-only")
                return 1
    finally:
        conn.close()

    states = ("andhra", "telangana") if args.state == "both" else (args.state,)
    grand_features = 0
    grand_upserted = 0

    print(f"Seeding roads registry (batch={args.batch_size}, dry_run={args.dry_run})")
    for sk in states:
        n_feat, n_ins = seed_state(
            sk,
            district_filter=args.district,
            batch_size=args.batch_size,
            dry_run=args.dry_run,
        )
        grand_features += n_feat
        grand_upserted += n_ins

    print(f"\nParsed {grand_features:,} segments; upserted {grand_upserted:,} rows")

    if not args.dry_run:
        if args.sync_status:
            sync_survey_status()
        if args.snap_potholes:
            snap_potholes()
        print_summary()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
